export * from './admin.service';
import { AdminService } from './admin.service';
export * from './backOfficeUser.service';
import { BackOfficeUserService } from './backOfficeUser.service';
export * from './buyer.service';
import { BuyerService } from './buyer.service';
export * from './car.service';
import { CarService } from './car.service';
export * from './color.service';
import { ColorService } from './color.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './feature.service';
import { FeatureService } from './feature.service';
export * from './front.service';
import { FrontService } from './front.service';
export * from './garage.service';
import { GarageService } from './garage.service';
export * from './inspection.service';
import { InspectionService } from './inspection.service';
export * from './openingTime.service';
import { OpeningTimeService } from './openingTime.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './rdv.service';
import { RdvService } from './rdv.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminService, BackOfficeUserService, BuyerService, CarService, ColorService, DefaultService, FeatureService, FrontService, GarageService, InspectionService, OpeningTimeService, QuestionService, RdvService, UserService];
