/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { AllCarsResponse } from '../model/allCarsResponse';
import { Car } from '../model/car';
import { DefaultResponse } from '../model/defaultResponse';
import { InlineResponse400 } from '../model/inlineResponse400';
import { OneCarResponse } from '../model/oneCarResponse';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class CarService {
  protected basePath = 'http://localhost/carswitch/public/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Return all cars
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public allCars(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<AllCarsResponse>;
  public allCars(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<AllCarsResponse>>;
  public allCars(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<AllCarsResponse>>;
  public allCars(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<AllCarsResponse>(
      'get',
      `${this.basePath}/cars`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Create a new car
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createCar(
    body?: Car,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneCarResponse>;
  public createCar(
    body?: Car,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneCarResponse>>;
  public createCar(
    body?: Car,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneCarResponse>>;
  public createCar(
    body?: Car,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneCarResponse>(
      'post',
      `${this.basePath}/car/create`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete a specifique Car by id
   *
   * @param carId The ID of a specifique car
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteCar(
    carId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<DefaultResponse>;
  public deleteCar(
    carId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<DefaultResponse>>;
  public deleteCar(
    carId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<DefaultResponse>>;
  public deleteCar(
    carId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (carId === null || carId === undefined) {
      throw new Error(
        'Required parameter carId was null or undefined when calling deleteCar.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<DefaultResponse>(
      'delete',
      `${this.basePath}/car/${encodeURIComponent(String(carId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete a specifique picture of car
   *
   * @param pictureId The ID of a specifique picture
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deletePictureOfCar(
    pictureId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>;
  public deletePictureOfCar(
    pictureId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public deletePictureOfCar(
    pictureId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public deletePictureOfCar(
    pictureId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (pictureId === null || pictureId === undefined) {
      throw new Error(
        'Required parameter pictureId was null or undefined when calling deletePictureOfCar.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'delete',
      `${this.basePath}/car/picture/${encodeURIComponent(String(pictureId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Edit a specifique Car by id
   *
   * @param carId The ID of a specifique car
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public editCar(
    carId: number,
    body?: Car,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneCarResponse>;
  public editCar(
    carId: number,
    body?: Car,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneCarResponse>>;
  public editCar(
    carId: number,
    body?: Car,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneCarResponse>>;
  public editCar(
    carId: number,
    body?: Car,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (carId === null || carId === undefined) {
      throw new Error(
        'Required parameter carId was null or undefined when calling editCar.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneCarResponse>(
      'put',
      `${this.basePath}/car/${encodeURIComponent(String(carId))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get detaille of a specifique car by id
   *
   * @param carId The ID of a specifique car
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getCarById(
    carId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneCarResponse>;
  public getCarById(
    carId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneCarResponse>>;
  public getCarById(
    carId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneCarResponse>>;
  public getCarById(
    carId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (carId === null || carId === undefined) {
      throw new Error(
        'Required parameter carId was null or undefined when calling getCarById.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<OneCarResponse>(
      'get',
      `${this.basePath}/car/${encodeURIComponent(String(carId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
