/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { AllFeaturesResponse } from '../model/allFeaturesResponse';
import { DefaultResponse } from '../model/defaultResponse';
import { Feature } from '../model/feature';
import { OneFeatureResponse } from '../model/oneFeatureResponse';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class FeatureService {
  protected basePath = 'http://localhost/carswitch/public/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get list of all features
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public allFeatures(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<AllFeaturesResponse>;
  public allFeatures(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<AllFeaturesResponse>>;
  public allFeatures(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<AllFeaturesResponse>>;
  public allFeatures(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<AllFeaturesResponse>(
      'get',
      `${this.basePath}/features`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Create a new feature
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createFeature(
    body?: Feature,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneFeatureResponse>;
  public createFeature(
    body?: Feature,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneFeatureResponse>>;
  public createFeature(
    body?: Feature,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneFeatureResponse>>;
  public createFeature(
    body?: Feature,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneFeatureResponse>(
      'post',
      `${this.basePath}/feature/create`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete a specifique feature by id
   *
   * @param featureId The ID of a specifique feature
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteFeature(
    featureId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<DefaultResponse>;
  public deleteFeature(
    featureId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<DefaultResponse>>;
  public deleteFeature(
    featureId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<DefaultResponse>>;
  public deleteFeature(
    featureId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (featureId === null || featureId === undefined) {
      throw new Error(
        'Required parameter featureId was null or undefined when calling deleteFeature.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<DefaultResponse>(
      'delete',
      `${this.basePath}/feature/${encodeURIComponent(String(featureId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Edit a specifique feature by ID
   *
   * @param featureId The ID of a specifique feature
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public editFeature(
    featureId: number,
    body?: Feature,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneFeatureResponse>;
  public editFeature(
    featureId: number,
    body?: Feature,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneFeatureResponse>>;
  public editFeature(
    featureId: number,
    body?: Feature,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneFeatureResponse>>;
  public editFeature(
    featureId: number,
    body?: Feature,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (featureId === null || featureId === undefined) {
      throw new Error(
        'Required parameter featureId was null or undefined when calling editFeature.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneFeatureResponse>(
      'put',
      `${this.basePath}/feature/${encodeURIComponent(String(featureId))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get detaille of a specifique feature by ID
   *
   * @param featureId The ID of a specifique feature
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getFeatureById(
    featureId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneFeatureResponse>;
  public getFeatureById(
    featureId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneFeatureResponse>>;
  public getFeatureById(
    featureId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneFeatureResponse>>;
  public getFeatureById(
    featureId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (featureId === null || featureId === undefined) {
      throw new Error(
        'Required parameter featureId was null or undefined when calling getFeatureById.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<OneFeatureResponse>(
      'get',
      `${this.basePath}/feature/${encodeURIComponent(String(featureId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
