/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { AllGaragesResponse } from '../model/allGaragesResponse';
import { DefaultResponse } from '../model/defaultResponse';
import { Garage } from '../model/garage';
import { OneGarageResponse } from '../model/oneGarageResponse';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class GarageService {
  protected basePath = 'http://localhost/carswitch/public/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get list of all garages
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public allGarages(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<AllGaragesResponse>;
  public allGarages(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<AllGaragesResponse>>;
  public allGarages(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<AllGaragesResponse>>;
  public allGarages(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<AllGaragesResponse>(
      'get',
      `${this.basePath}/garages`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Create a new garage
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createGarage(
    body?: Garage,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneGarageResponse>;
  public createGarage(
    body?: Garage,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneGarageResponse>>;
  public createGarage(
    body?: Garage,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneGarageResponse>>;
  public createGarage(
    body?: Garage,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneGarageResponse>(
      'post',
      `${this.basePath}/garage/create`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete a specifique Garage by id
   *
   * @param garageId The ID of a specifique garage
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteGarage(
    garageId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<DefaultResponse>;
  public deleteGarage(
    garageId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<DefaultResponse>>;
  public deleteGarage(
    garageId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<DefaultResponse>>;
  public deleteGarage(
    garageId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (garageId === null || garageId === undefined) {
      throw new Error(
        'Required parameter garageId was null or undefined when calling deleteGarage.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<DefaultResponse>(
      'delete',
      `${this.basePath}/garage/${encodeURIComponent(String(garageId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Edit a specifique garage by ID
   *
   * @param garageId The ID of a specifique garage
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public editGarage(
    garageId: number,
    body?: Garage,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneGarageResponse>;
  public editGarage(
    garageId: number,
    body?: Garage,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneGarageResponse>>;
  public editGarage(
    garageId: number,
    body?: Garage,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneGarageResponse>>;
  public editGarage(
    garageId: number,
    body?: Garage,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (garageId === null || garageId === undefined) {
      throw new Error(
        'Required parameter garageId was null or undefined when calling editGarage.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneGarageResponse>(
      'put',
      `${this.basePath}/garage/${encodeURIComponent(String(garageId))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get detaille of a specifique garage by ID
   *
   * @param garageId The ID of a specifique garage
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getGarageById(
    garageId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneGarageResponse>;
  public getGarageById(
    garageId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneGarageResponse>>;
  public getGarageById(
    garageId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneGarageResponse>>;
  public getGarageById(
    garageId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (garageId === null || garageId === undefined) {
      throw new Error(
        'Required parameter garageId was null or undefined when calling getGarageById.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<OneGarageResponse>(
      'get',
      `${this.basePath}/garage/${encodeURIComponent(String(garageId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
