/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { AllOpeningTimesResponse } from '../model/allOpeningTimesResponse';
import { DefaultResponse } from '../model/defaultResponse';
import { OneOpeningTimeResponse } from '../model/oneOpeningTimeResponse';
import { OpeningTime } from '../model/openingTime';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class OpeningTimeService {
  protected basePath = 'http://localhost/carswitch/public/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get list of all opening time
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public allOpeningTimes(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<AllOpeningTimesResponse>;
  public allOpeningTimes(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<AllOpeningTimesResponse>>;
  public allOpeningTimes(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<AllOpeningTimesResponse>>;
  public allOpeningTimes(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<AllOpeningTimesResponse>(
      'get',
      `${this.basePath}/opening_times`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Create a new Opening Time
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createOpeningTime(
    body?: OpeningTime,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneOpeningTimeResponse>;
  public createOpeningTime(
    body?: OpeningTime,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneOpeningTimeResponse>>;
  public createOpeningTime(
    body?: OpeningTime,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneOpeningTimeResponse>>;
  public createOpeningTime(
    body?: OpeningTime,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneOpeningTimeResponse>(
      'post',
      `${this.basePath}/opening_time/create`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete a specifique Timing by id
   *
   * @param openingTimeId The ID of a specifique Timing
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteOpeningTime(
    openingTimeId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<DefaultResponse>;
  public deleteOpeningTime(
    openingTimeId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<DefaultResponse>>;
  public deleteOpeningTime(
    openingTimeId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<DefaultResponse>>;
  public deleteOpeningTime(
    openingTimeId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (openingTimeId === null || openingTimeId === undefined) {
      throw new Error(
        'Required parameter openingTimeId was null or undefined when calling deleteOpeningTime.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<DefaultResponse>(
      'delete',
      `${this.basePath}/opening_time/${encodeURIComponent(
        String(openingTimeId)
      )}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Edit a specifique Timing by ID
   *
   * @param openingTimeId The ID of a specifique Timing
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public editOpeningTime(
    openingTimeId: number,
    body?: OpeningTime,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneOpeningTimeResponse>;
  public editOpeningTime(
    openingTimeId: number,
    body?: OpeningTime,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneOpeningTimeResponse>>;
  public editOpeningTime(
    openingTimeId: number,
    body?: OpeningTime,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneOpeningTimeResponse>>;
  public editOpeningTime(
    openingTimeId: number,
    body?: OpeningTime,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (openingTimeId === null || openingTimeId === undefined) {
      throw new Error(
        'Required parameter openingTimeId was null or undefined when calling editOpeningTime.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<OneOpeningTimeResponse>(
      'put',
      `${this.basePath}/opening_time/${encodeURIComponent(
        String(openingTimeId)
      )}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get detaille of a specifique Timing by ID
   *
   * @param openingTimeId The ID of a specifique Timing
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getOpeningTimeById(
    openingTimeId: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OneOpeningTimeResponse>;
  public getOpeningTimeById(
    openingTimeId: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<OneOpeningTimeResponse>>;
  public getOpeningTimeById(
    openingTimeId: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<OneOpeningTimeResponse>>;
  public getOpeningTimeById(
    openingTimeId: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (openingTimeId === null || openingTimeId === undefined) {
      throw new Error(
        'Required parameter openingTimeId was null or undefined when calling getOpeningTimeById.'
      );
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.configuration.accessToken) {
      const accessToken =
        typeof this.configuration.accessToken === 'function'
          ? this.configuration.accessToken()
          : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<OneOpeningTimeResponse>(
      'get',
      `${this.basePath}/opening_time/${encodeURIComponent(
        String(openingTimeId)
      )}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
