/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Garage { 
    readonly id?: number;
    name?: string;
    wilayaId?: number;
    address?: string;
    sundayTime?: number;
    mondayTime?: number;
    tuesdayTime?: number;
    wednesdayTime?: number;
    thursdayTime?: number;
    fridayTime?: number;
    saturdayTime?: number;
    readonly createdAt?: Date;
}