/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Inspection { 
    readonly id?: number;
    carId?: number;
    rdvId?: number;
    adminId?: number;
    garageId?: number;
    type?: Inspection.TypeEnum;
    readonly createdAt?: Date;
}
export namespace Inspection {
    export type TypeEnum = 'first_level' | 'second_level' | 'both';
    export const TypeEnum = {
        FirstLevel: 'first_level' as TypeEnum,
        SecondLevel: 'second_level' as TypeEnum,
        Both: 'both' as TypeEnum
    };
}