/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Question { 
    readonly id?: number;
    questionFr?: string;
    questionEn?: string;
    questionAr?: string;
    type?: Question.TypeEnum;
    readonly createdAt?: Date;
}
export namespace Question {
    export type TypeEnum = 'exterior' | 'interior' | 'engine' | 'driving' | 'electronic_diagnostic' | 'tyre_and_brake' | 'scratches' | 'document' | 'underbody';
    export const TypeEnum = {
        Exterior: 'exterior' as TypeEnum,
        Interior: 'interior' as TypeEnum,
        Engine: 'engine' as TypeEnum,
        Driving: 'driving' as TypeEnum,
        ElectronicDiagnostic: 'electronic_diagnostic' as TypeEnum,
        TyreAndBrake: 'tyre_and_brake' as TypeEnum,
        Scratches: 'scratches' as TypeEnum,
        Document: 'document' as TypeEnum,
        Underbody: 'underbody' as TypeEnum
    };
}