/**
 * SwitchCar API
 * SwitchCar API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Rdv { 
    readonly id?: number;
    carId?: number;
    adminId?: number;
    garageId?: number;
    address?: string;
    rdvDate?: string;
    rdvTime?: string;
    rdvType?: Rdv.RdvTypeEnum;
    expectedPayment?: number;
    paymentIsCollected?: boolean;
    note?: string;
    readonly createdAt?: Date;
}
export namespace Rdv {
    export type RdvTypeEnum = 'inspection' | 'sale' | 'visit' | 'unavaibility';
    export const RdvTypeEnum = {
        Inspection: 'inspection' as RdvTypeEnum,
        Sale: 'sale' as RdvTypeEnum,
        Visit: 'visit' as RdvTypeEnum,
        Unavaibility: 'unavaibility' as RdvTypeEnum
    };
}